# Code generated by SdkContractGenerator. DO NOT EDIT.

CONTRACT = {
    "edit-video": {
        "models": ["runway-aleph"],
        "fields_by_model": {
            "runway-aleph": {
                "aspect_ratio": {
                    "enum": ["16:9", "9:16", "4:3", "3:4", "1:1", "21:9"]
                },
                "prompt": {
                    "required": True
                },
                "seed": {
                    "type": "integer"
                },
                "source_video_url": {
                    "required": True
                }
            }
        }
    }
}
