package runwayaleph

// Code generated by SdkContractGenerator. DO NOT EDIT.

var contractSchema = map[string]any{"edit-video": map[string]any{"models": []any{"runway-aleph"}, "fields_by_model": map[string]any{"runway-aleph": map[string]any{"aspect_ratio": map[string]any{"enum": []any{"16:9", "9:16", "4:3", "3:4", "1:1", "21:9"}}, "prompt": map[string]any{"required": true}, "seed": map[string]any{"type": "integer"}, "source_video_url": map[string]any{"required": true}}}}}
