# frozen_string_literal: true

# Code generated by SdkContractGenerator. DO NOT EDIT.

module RunApi
  module RunwayAleph
    CONTRACT = {
      "edit-video" => {
        "models" => ["runway-aleph"],
        "fields_by_model" => {
          "runway-aleph" => {
            "aspect_ratio" => {
              "enum" => ["16:9", "9:16", "4:3", "3:4", "1:1", "21:9"]
            },
            "prompt" => {
              "required" => true
            },
            "seed" => {
              "type" => "integer"
            },
            "source_video_url" => {
              "required" => true
            }
          }
        }
      }
    }.freeze
  end
end
